#pragma once

#define CHARYBDIS_MINIMUM_DEFAULT_DPI 0
#define CHARYBDIS_DEFAULT_DPI_CONFIG_STEP 200

#define CHARYBDIS_MINIMUM_SNIPING_DPI 0
#define CHARYBDIS_SNIPING_DPI_CONFIG_STEP 100

#define SPLIT_LAYER_STATE_ENABLE
